//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorytmySzkolne.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceManagerTest.Languages.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorization.
        /// </summary>
        internal static string aCzynniki {
            get {
                return ResourceManager.GetString("aCzynniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highest common factor.
        /// </summary>
        internal static string aDzielnik {
            get {
                return ResourceManager.GetString("aDzielnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string aLiczba {
            get {
                return ResourceManager.GetString("aLiczba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI.
        /// </summary>
        internal static string aPI {
            get {
                return ResourceManager.GetString("aPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime number?.
        /// </summary>
        internal static string aPierwsza {
            get {
                return ResourceManager.GetString("aPierwsza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of integers from this range.
        /// </summary>
        internal static string aPrzedział {
            get {
                return ResourceManager.GetString("aPrzedział", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowest common multiple.
        /// </summary>
        internal static string aWielokrotność {
            get {
                return ResourceManager.GetString("aWielokrotność", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string aWynik {
            get {
                return ResourceManager.GetString("aWynik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string aX {
            get {
                return ResourceManager.GetString("aX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string eBłąd {
            get {
                return ResourceManager.GetString("eBłąd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A wrong number of points has been given! The default value will be set..
        /// </summary>
        internal static string emsgAproksymacjaPunkty {
            get {
                return ResourceManager.GetString("emsgAproksymacjaPunkty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error of argument/s!.
        /// </summary>
        internal static string emsgBłądArgumentu {
            get {
                return ResourceManager.GetString("emsgBłądArgumentu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function set! Would you like to randomize an equation?.
        /// </summary>
        internal static string emsgBłądFunkcji {
            get {
                return ResourceManager.GetString("emsgBłądFunkcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        internal static string emsgException {
            get {
                return ResourceManager.GetString("emsgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format of input..
        /// </summary>
        internal static string emsgFormatWejścia {
            get {
                return ResourceManager.GetString("emsgFormatWejścia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in line segment amount..
        /// </summary>
        internal static string emsgIlośćOdcinków {
            get {
                return ResourceManager.GetString("emsgIlośćOdcinków", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No function equation set!.
        /// </summary>
        internal static string emsgNiePodanoFunkcji {
            get {
                return ResourceManager.GetString("emsgNiePodanoFunkcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum base of a numeral system is 36 !.
        /// </summary>
        internal static string emsgPodstawaSystemu {
            get {
                return ResourceManager.GetString("emsgPodstawaSystemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An incorrect number has been given! The default value will be set..
        /// </summary>
        internal static string emsgSierpinskiPoziomy {
            get {
                return ResourceManager.GetString("emsgSierpinskiPoziomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string eNieZnaleziono {
            get {
                return ResourceManager.GetString("eNieZnaleziono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string eSukces {
            get {
                return ResourceManager.GetString("eSukces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random function equation set successfully..
        /// </summary>
        internal static string eWylosowano {
            get {
                return ResourceManager.GetString("eWylosowano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative method.
        /// </summary>
        internal static string fAlternatywa {
            get {
                return ResourceManager.GetString("fAlternatywa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine.
        /// </summary>
        internal static string fCos {
            get {
                return ResourceManager.GetString("fCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotangent.
        /// </summary>
        internal static string fCtg {
            get {
                return ResourceManager.GetString("fCtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize.
        /// </summary>
        internal static string fLosuj {
            get {
                return ResourceManager.GetString("fLosuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root.
        /// </summary>
        internal static string fPierwiastek {
            get {
                return ResourceManager.GetString("fPierwiastek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        internal static string fSin {
            get {
                return ResourceManager.GetString("fSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent.
        /// </summary>
        internal static string fTg {
            get {
                return ResourceManager.GetString("fTg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polynomial.
        /// </summary>
        internal static string fWielomian {
            get {
                return ResourceManager.GetString("fWielomian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rational function.
        /// </summary>
        internal static string fWymierna {
            get {
                return ResourceManager.GetString("fWymierna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to put down eight bishops..
        /// </summary>
        internal static string hFailH {
            get {
                return ResourceManager.GetString("hFailH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to place the knight on all tiles..
        /// </summary>
        internal static string hFailS {
            get {
                return ResourceManager.GetString("hFailS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you put down eight bishops!.
        /// </summary>
        internal static string hGratulacjeH {
            get {
                return ResourceManager.GetString("hGratulacjeH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you placed the knight on all tiles exactly once!.
        /// </summary>
        internal static string hGratulacjeS {
            get {
                return ResourceManager.GetString("hGratulacjeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of bishops.
        /// </summary>
        internal static string hIlośćH {
            get {
                return ResourceManager.GetString("hIlośćH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Knights.
        /// </summary>
        internal static string hIlośćS {
            get {
                return ResourceManager.GetString("hIlośćS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place a bishop here!.
        /// </summary>
        internal static string hNieMożnaH {
            get {
                return ResourceManager.GetString("hNieMożnaH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot place the knight here!.
        /// </summary>
        internal static string hNieMożnaS {
            get {
                return ResourceManager.GetString("hNieMożnaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to start over?.
        /// </summary>
        internal static string hRestart {
            get {
                return ResourceManager.GetString("hRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the accuracy (amount of line segments) and the start and end of a range to get the area under the curve..
        /// </summary>
        internal static string iCałka {
            get {
                return ResourceManager.GetString("iCałka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a number to get its factorization (in a non-decreasing order).
        /// </summary>
        internal static string iCzynnikiPierwsze {
            get {
                return ResourceManager.GetString("iCzynnikiPierwsze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function: .
        /// </summary>
        internal static string iFunkcja {
            get {
                return ResourceManager.GetString("iFunkcja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! Shit knows if this works. Are you sure you want to try?.
        /// </summary>
        internal static string iNiepewne {
            get {
                return ResourceManager.GetString("iNiepewne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide 2 numbers to get their HCF and LCM..
        /// </summary>
        internal static string iNWD {
            get {
                return ResourceManager.GetString("iNWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an expression in regular notation to get its equivalent in RPN (Reverse Polish Notation).
        /// </summary>
        internal static string iONPNa {
            get {
                return ResourceManager.GetString("iONPNa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an expression in RPN (Reverse Polish Notation) to get its value..
        /// </summary>
        internal static string iONPWartość {
            get {
                return ResourceManager.GetString("iONPWartość", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an expression in RPN (Reverse Polish Notation) to get its equivalent in regular notation..
        /// </summary>
        internal static string iONPZ {
            get {
                return ResourceManager.GetString("iONPZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string iOstrzeżenie {
            get {
                return ResourceManager.GetString("iOstrzeżenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the accuracy and a number to get its square root. Default value: 0.0001. Both period and comma are allowed..
        /// </summary>
        internal static string iPierwiastek {
            get {
                return ResourceManager.GetString("iPierwiastek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a number to check whether it&apos;s prime or not..
        /// </summary>
        internal static string iPierwsza {
            get {
                return ResourceManager.GetString("iPierwsza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide 2 numbers to get a random number from that range..
        /// </summary>
        internal static string iRNG {
            get {
                return ResourceManager.GetString("iRNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a number to get its factorial (the factorial can have up to ~600 million digits, but such an attempt can end very, very badly!).
        /// </summary>
        internal static string iSilnia {
            get {
                return ResourceManager.GetString("iSilnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a number to get the sum of its digits..
        /// </summary>
        internal static string iSumaCyfr {
            get {
                return ResourceManager.GetString("iSumaCyfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a number to get the sum of all its prime factors..
        /// </summary>
        internal static string iSumaDzielników {
            get {
                return ResourceManager.GetString("iSumaDzielników", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the start and end of a range to get a number that is the sum of all integers from that range..
        /// </summary>
        internal static string iSumaPrzedziału {
            get {
                return ResourceManager.GetString("iSumaPrzedziału", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of function: .
        /// </summary>
        internal static string iTypFunkcji {
            get {
                return ResourceManager.GetString("iTypFunkcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the start and end of a range to find the root. Do note that it is possible only when the values of the function at the start and end of the range are of different signs. Also remember to set a function equation before starting the algorithm. If the equation hasn&apos;t been set, it is possible to generate a random one..
        /// </summary>
        internal static string iZerowe {
            get {
                return ResourceManager.GetString("iZerowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To RPN.
        /// </summary>
        internal static string oNaONP {
            get {
                return ResourceManager.GetString("oNaONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of a RPN expression.
        /// </summary>
        internal static string oWartosc {
            get {
                return ResourceManager.GetString("oWartosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From RPN.
        /// </summary>
        internal static string oZONP {
            get {
                return ResourceManager.GetString("oZONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an argument....
        /// </summary>
        internal static string pArgument {
            get {
                return ResourceManager.GetString("pArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate!.
        /// </summary>
        internal static string pOblicz {
            get {
                return ResourceManager.GetString("pOblicz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute!.
        /// </summary>
        internal static string pWykonaj {
            get {
                return ResourceManager.GetString("pWykonaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI approximation.
        /// </summary>
        internal static string strAproksymacja {
            get {
                return ResourceManager.GetString("strAproksymacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integral.
        /// </summary>
        internal static string strCalka {
            get {
                return ResourceManager.GetString("strCalka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area under the curve.
        /// </summary>
        internal static string strCalka2 {
            get {
                return ResourceManager.GetString("strCalka2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to quit the application?.
        /// </summary>
        internal static string strCzyChceszWyjść {
            get {
                return ResourceManager.GetString("strCzyChceszWyjść", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime factors.
        /// </summary>
        internal static string strCzynnikiPierwsze {
            get {
                return ResourceManager.GetString("strCzynnikiPierwsze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euklides&apos; Algorithm.
        /// </summary>
        internal static string strEuklides {
            get {
                return ResourceManager.GetString("strEuklides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homepage.
        /// </summary>
        internal static string strGlowna {
            get {
                return ResourceManager.GetString("strGlowna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide lower bound.
        /// </summary>
        internal static string strGranica1 {
            get {
                return ResourceManager.GetString("strGranica1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide upper bound.
        /// </summary>
        internal static string strGranica2 {
            get {
                return ResourceManager.GetString("strGranica2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string strInfo {
            get {
                return ResourceManager.GetString("strInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is a compilation of most algorithms that we did during Computing classes in second grade of highschool. It handles several basic hotkeys..
        /// </summary>
        internal static string strInfo1 {
            get {
                return ResourceManager.GetString("strInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC: quit the application
        ///1-8: choice of a given algorithm(only on the algorithm selection screen)
        ///TAB: next control.
        /// </summary>
        internal static string strInfo2 {
            get {
                return ResourceManager.GetString("strInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classical algorithms.
        /// </summary>
        internal static string strKlasyczne {
            get {
                return ResourceManager.GetString("strKlasyczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPN.
        /// </summary>
        internal static string strONP {
            get {
                return ResourceManager.GetString("strONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root.
        /// </summary>
        internal static string strPierwiastek {
            get {
                return ResourceManager.GetString("strPierwiastek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square root of a number.
        /// </summary>
        internal static string strPierwiastek2 {
            get {
                return ResourceManager.GetString("strPierwiastek2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prime number.
        /// </summary>
        internal static string strPierwsza {
            get {
                return ResourceManager.GetString("strPierwsza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide an argument.
        /// </summary>
        internal static string strPodajArgument {
            get {
                return ResourceManager.GetString("strPodajArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the accuracy.
        /// </summary>
        internal static string strPodajEpsilon {
            get {
                return ResourceManager.GetString("strPodajEpsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the amount of line segments.
        /// </summary>
        internal static string strPodajIloscOdcinkow {
            get {
                return ResourceManager.GetString("strPodajIloscOdcinkow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a number.
        /// </summary>
        internal static string strPodajLiczbę {
            get {
                return ResourceManager.GetString("strPodajLiczbę", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the first number.
        /// </summary>
        internal static string strPodajLiczbę1 {
            get {
                return ResourceManager.GetString("strPodajLiczbę1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the second number.
        /// </summary>
        internal static string strPodajLiczbę2 {
            get {
                return ResourceManager.GetString("strPodajLiczbę2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string strProjekty {
            get {
                return ResourceManager.GetString("strProjekty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the start of a range.
        /// </summary>
        internal static string strPrzedział1 {
            get {
                return ResourceManager.GetString("strPrzedział1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide the end of a range.
        /// </summary>
        internal static string strPrzedział2 {
            get {
                return ResourceManager.GetString("strPrzedział2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string strRestart {
            get {
                return ResourceManager.GetString("strRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Number Generator.
        /// </summary>
        internal static string strRNG {
            get {
                return ResourceManager.GetString("strRNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorial.
        /// </summary>
        internal static string strSilnia {
            get {
                return ResourceManager.GetString("strSilnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of digits.
        /// </summary>
        internal static string strSumaCyfr {
            get {
                return ResourceManager.GetString("strSumaCyfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of prime factors.
        /// </summary>
        internal static string strSumaDzielnikow {
            get {
                return ResourceManager.GetString("strSumaDzielnikow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of a range.
        /// </summary>
        internal static string strSumaPrzedzialu {
            get {
                return ResourceManager.GetString("strSumaPrzedzialu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric systems.
        /// </summary>
        internal static string strSystemy {
            get {
                return ResourceManager.GetString("strSystemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set function.
        /// </summary>
        internal static string strUstaw {
            get {
                return ResourceManager.GetString("strUstaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string strWyjście {
            get {
                return ResourceManager.GetString("strWyjście", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greedy algorithms.
        /// </summary>
        internal static string strZachlanne {
            get {
                return ResourceManager.GetString("strZachlanne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root of function.
        /// </summary>
        internal static string strZerowe {
            get {
                return ResourceManager.GetString("strZerowe", resourceCulture);
            }
        }
    }
}
