//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgorytmySzkolne.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceManagerTest.Languages.pl", typeof(pl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozkład na czynniki.
        /// </summary>
        internal static string aCzynniki {
            get {
                return ResourceManager.GetString("aCzynniki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Największy wspólny dzielnik.
        /// </summary>
        internal static string aDzielnik {
            get {
                return ResourceManager.GetString("aDzielnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba.
        /// </summary>
        internal static string aLiczba {
            get {
                return ResourceManager.GetString("aLiczba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PI.
        /// </summary>
        internal static string aPI {
            get {
                return ResourceManager.GetString("aPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba pierwsza?.
        /// </summary>
        internal static string aPierwsza {
            get {
                return ResourceManager.GetString("aPierwsza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma liczb całkowitych z tego przedziału.
        /// </summary>
        internal static string aPrzedział {
            get {
                return ResourceManager.GetString("aPrzedział", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najmniejsza wielokrotność.
        /// </summary>
        internal static string aWielokrotność {
            get {
                return ResourceManager.GetString("aWielokrotność", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wynik.
        /// </summary>
        internal static string aWynik {
            get {
                return ResourceManager.GetString("aWynik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string aX {
            get {
                return ResourceManager.GetString("aX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd.
        /// </summary>
        internal static string eBłąd {
            get {
                return ResourceManager.GetString("eBłąd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podano niewłaściwą ilość punktów! Zostanie przydzielona wartość domyślna..
        /// </summary>
        internal static string emsgAproksymacjaPunkty {
            get {
                return ResourceManager.GetString("emsgAproksymacjaPunkty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd argumentu/ów!.
        /// </summary>
        internal static string emsgBłądArgumentu {
            get {
                return ResourceManager.GetString("emsgBłądArgumentu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podano funkcji! Czy chcesz wylosować wzór?.
        /// </summary>
        internal static string emsgBłądFunkcji {
            get {
                return ResourceManager.GetString("emsgBłądFunkcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coś poszło nie tak..
        /// </summary>
        internal static string emsgException {
            get {
                return ResourceManager.GetString("emsgException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieprawidłowy format wejścia..
        /// </summary>
        internal static string emsgFormatWejścia {
            get {
                return ResourceManager.GetString("emsgFormatWejścia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Błąd w ilości odcinków..
        /// </summary>
        internal static string emsgIlośćOdcinków {
            get {
                return ResourceManager.GetString("emsgIlośćOdcinków", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podano wzoru funkcji!.
        /// </summary>
        internal static string emsgNiePodanoFunkcji {
            get {
                return ResourceManager.GetString("emsgNiePodanoFunkcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maksymalna podstawa systemu liczbowego to 36 !.
        /// </summary>
        internal static string emsgPodstawaSystemu {
            get {
                return ResourceManager.GetString("emsgPodstawaSystemu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie podano poprawnej liczby! Zostanie ustawiona wartość domyślna..
        /// </summary>
        internal static string emsgSierpinskiPoziomy {
            get {
                return ResourceManager.GetString("emsgSierpinskiPoziomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono.
        /// </summary>
        internal static string eNieZnaleziono {
            get {
                return ResourceManager.GetString("eNieZnaleziono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sukces.
        /// </summary>
        internal static string eSukces {
            get {
                return ResourceManager.GetString("eSukces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wylosowano wzór funkcji pomyślnie..
        /// </summary>
        internal static string eWylosowano {
            get {
                return ResourceManager.GetString("eWylosowano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternatywna metoda.
        /// </summary>
        internal static string fAlternatywa {
            get {
                return ResourceManager.GetString("fAlternatywa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosinus.
        /// </summary>
        internal static string fCos {
            get {
                return ResourceManager.GetString("fCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cotangens.
        /// </summary>
        internal static string fCtg {
            get {
                return ResourceManager.GetString("fCtg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losuj.
        /// </summary>
        internal static string fLosuj {
            get {
                return ResourceManager.GetString("fLosuj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwiastek.
        /// </summary>
        internal static string fPierwiastek {
            get {
                return ResourceManager.GetString("fPierwiastek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinus.
        /// </summary>
        internal static string fSin {
            get {
                return ResourceManager.GetString("fSin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangens.
        /// </summary>
        internal static string fTg {
            get {
                return ResourceManager.GetString("fTg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wielomian.
        /// </summary>
        internal static string fWielomian {
            get {
                return ResourceManager.GetString("fWielomian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja wymierna.
        /// </summary>
        internal static string fWymierna {
            get {
                return ResourceManager.GetString("fWymierna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało ci się postawić ośmiu hetmanów..
        /// </summary>
        internal static string hFailH {
            get {
                return ResourceManager.GetString("hFailH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie udało ci się postawić skoczka na każdym polu..
        /// </summary>
        internal static string hFailS {
            get {
                return ResourceManager.GetString("hFailS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulacje, udało Ci się postawić ośmiu hetmanów!.
        /// </summary>
        internal static string hGratulacjeH {
            get {
                return ResourceManager.GetString("hGratulacjeH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulacje, udało ci się postawić skoczka na każdym miejscu dokładnie jeden raz!.
        /// </summary>
        internal static string hGratulacjeS {
            get {
                return ResourceManager.GetString("hGratulacjeS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość hetmanów.
        /// </summary>
        internal static string hIlośćH {
            get {
                return ResourceManager.GetString("hIlośćH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ilość skoczków.
        /// </summary>
        internal static string hIlośćS {
            get {
                return ResourceManager.GetString("hIlośćS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można tu postawić hetmana!.
        /// </summary>
        internal static string hNieMożnaH {
            get {
                return ResourceManager.GetString("hNieMożnaH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można tu przesunąć skoczka!.
        /// </summary>
        internal static string hNieMożnaS {
            get {
                return ResourceManager.GetString("hNieMożnaS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz zacząć od nowa?.
        /// </summary>
        internal static string hRestart {
            get {
                return ResourceManager.GetString("hRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj dokładność(ilość odcinków) oraz początek i koniec przedziału by otrzymać pole pod wykresem podanej funkcji. Pamiętaj o podaniu wzoru funkcji przed uruchomieniem algorytmu. Jeżeli nie podano wzoru, istnieje możliwość jego wylosowania.Domyślna wartość: 10000 lub więcej..
        /// </summary>
        internal static string iCałka {
            get {
                return ResourceManager.GetString("iCałka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę aby uzyskać jej rozkład na czynniki pierwsze (w kolejności niemalejącej).
        /// </summary>
        internal static string iCzynnikiPierwsze {
            get {
                return ResourceManager.GetString("iCzynnikiPierwsze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funkcja: .
        /// </summary>
        internal static string iFunkcja {
            get {
                return ResourceManager.GetString("iFunkcja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uwaga! Chuj wie czy to działa. Czy na pewno chcesz spróbować?.
        /// </summary>
        internal static string iNiepewne {
            get {
                return ResourceManager.GetString("iNiepewne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj 2 liczby by uzyskać ich NWW i NWD..
        /// </summary>
        internal static string iNWD {
            get {
                return ResourceManager.GetString("iNWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wyrażenie w notacji normalnej aby uzyskać jego odpowiednik w ONP.
        ///Przykład: (2+3)*4
        ///Wynik: 2 3 + 4 *.
        /// </summary>
        internal static string iONPNa {
            get {
                return ResourceManager.GetString("iONPNa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wyrażenie w ONP aby uzyskać jego wartość.
        ///Przykład: 2 3 + 4 *
        ///Wynik: 20.
        /// </summary>
        internal static string iONPWartość {
            get {
                return ResourceManager.GetString("iONPWartość", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj wyrażenie w ONP aby uzyskać jego odpowiednik w notacji normalnej.
        ///Przykład: 2 3 + 4 *
        ///Wynik: (2+3)*4.
        /// </summary>
        internal static string iONPZ {
            get {
                return ResourceManager.GetString("iONPZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostrzeżenie.
        /// </summary>
        internal static string iOstrzeżenie {
            get {
                return ResourceManager.GetString("iOstrzeżenie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj dokładność obliczeń oraz liczbę aby otrzymać jej pierwiastek kwadratowy. Domyślna wartość: 0,0001 lub mniej. Dozwolone jest zarówno podawanie z kropką, jak i z przecinkiem..
        /// </summary>
        internal static string iPierwiastek {
            get {
                return ResourceManager.GetString("iPierwiastek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę aby sprawdzić, czy jest ona pierwsza..
        /// </summary>
        internal static string iPierwsza {
            get {
                return ResourceManager.GetString("iPierwsza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj 2 liczby by uzyskać losową liczbę całkowitą z tego przedziału (obustronnie domkniętego).
        /// </summary>
        internal static string iRNG {
            get {
                return ResourceManager.GetString("iRNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę aby uzyskać jej silnię (silnia może mieć maksymalnie ~600 milionów cyfr, ale próba taka może skończyć się bardzo, bardzo źle!).
        /// </summary>
        internal static string iSilnia {
            get {
                return ResourceManager.GetString("iSilnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę aby uzyskać sumę wszystkich jej cyfr..
        /// </summary>
        internal static string iSumaCyfr {
            get {
                return ResourceManager.GetString("iSumaCyfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę aby uzyskać sumę jej dzielników naturalnych..
        /// </summary>
        internal static string iSumaDzielników {
            get {
                return ResourceManager.GetString("iSumaDzielników", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj początek i koniec przedziału aby uzyskać liczbę będącą sumą wszystkich liczb całkowitych z tego przedziału (przedział jest obustronnie domknięty).
        /// </summary>
        internal static string iSumaPrzedziału {
            get {
                return ResourceManager.GetString("iSumaPrzedziału", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ funkcji: .
        /// </summary>
        internal static string iTypFunkcji {
            get {
                return ResourceManager.GetString("iTypFunkcji", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj początek i koniec przedziału by znaleźć miejsce zerowe. Pamiętaj, że jest to możliwe tylko gdy wartość funkcji na początku i końcu przedziału mają różne znaki. Pamiętaj również o podaniu wzoru funkcji przed uruchomieniem algorytmu. Jeżeli nie podano wzoru, istnieje możliwość jego wylosowania..
        /// </summary>
        internal static string iZerowe {
            get {
                return ResourceManager.GetString("iZerowe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na ONP.
        /// </summary>
        internal static string oNaONP {
            get {
                return ResourceManager.GetString("oNaONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartość wyrażenia w ONP.
        /// </summary>
        internal static string oWartosc {
            get {
                return ResourceManager.GetString("oWartosc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z ONP.
        /// </summary>
        internal static string oZONP {
            get {
                return ResourceManager.GetString("oZONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj argument....
        /// </summary>
        internal static string pArgument {
            get {
                return ResourceManager.GetString("pArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblicz!.
        /// </summary>
        internal static string pOblicz {
            get {
                return ResourceManager.GetString("pOblicz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wykonaj!.
        /// </summary>
        internal static string pWykonaj {
            get {
                return ResourceManager.GetString("pWykonaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aproksymacja PI.
        /// </summary>
        internal static string strAproksymacja {
            get {
                return ResourceManager.GetString("strAproksymacja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Całka.
        /// </summary>
        internal static string strCalka {
            get {
                return ResourceManager.GetString("strCalka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pole pod wykresem.
        /// </summary>
        internal static string strCalka2 {
            get {
                return ResourceManager.GetString("strCalka2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czy chcesz wyjść z aplikacji?.
        /// </summary>
        internal static string strCzyChceszWyjść {
            get {
                return ResourceManager.GetString("strCzyChceszWyjść", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czynniki pierwsze.
        /// </summary>
        internal static string strCzynnikiPierwsze {
            get {
                return ResourceManager.GetString("strCzynnikiPierwsze", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorytm Euklidesa.
        /// </summary>
        internal static string strEuklides {
            get {
                return ResourceManager.GetString("strEuklides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strona główna.
        /// </summary>
        internal static string strGlowna {
            get {
                return ResourceManager.GetString("strGlowna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj dolną granicę.
        /// </summary>
        internal static string strGranica1 {
            get {
                return ResourceManager.GetString("strGranica1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj górną granicę.
        /// </summary>
        internal static string strGranica2 {
            get {
                return ResourceManager.GetString("strGranica2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informacje.
        /// </summary>
        internal static string strInfo {
            get {
                return ResourceManager.GetString("strInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplikacja będąca kompilacją większości algorytmów które pisaliśmy na lekcjach informatyki w klasie 2.liceum w roku szkolnym 2017 / 2018. Obsługuje kilka podstawowych skrótów klawiszowych..
        /// </summary>
        internal static string strInfo1 {
            get {
                return ResourceManager.GetString("strInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESC: wyjście z aplikacji
        ///1 - 8: wybór danego algorytmu(tylko na ekranie wyboru algorytmów)
        ///TAB: następna kontrolka.
        /// </summary>
        internal static string strInfo2 {
            get {
                return ResourceManager.GetString("strInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorytmy klasyczne.
        /// </summary>
        internal static string strKlasyczne {
            get {
                return ResourceManager.GetString("strKlasyczne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONP.
        /// </summary>
        internal static string strONP {
            get {
                return ResourceManager.GetString("strONP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwiastek kwadratowy.
        /// </summary>
        internal static string strPierwiastek {
            get {
                return ResourceManager.GetString("strPierwiastek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pierwiastek kwadratowy z liczby.
        /// </summary>
        internal static string strPierwiastek2 {
            get {
                return ResourceManager.GetString("strPierwiastek2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liczba pierwsza.
        /// </summary>
        internal static string strPierwsza {
            get {
                return ResourceManager.GetString("strPierwsza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj argument.
        /// </summary>
        internal static string strPodajArgument {
            get {
                return ResourceManager.GetString("strPodajArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj dokładność.
        /// </summary>
        internal static string strPodajEpsilon {
            get {
                return ResourceManager.GetString("strPodajEpsilon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj ilość odcinków.
        /// </summary>
        internal static string strPodajIloscOdcinkow {
            get {
                return ResourceManager.GetString("strPodajIloscOdcinkow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj liczbę.
        /// </summary>
        internal static string strPodajLiczbę {
            get {
                return ResourceManager.GetString("strPodajLiczbę", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj pierwszą liczbę.
        /// </summary>
        internal static string strPodajLiczbę1 {
            get {
                return ResourceManager.GetString("strPodajLiczbę1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj drugą liczbę.
        /// </summary>
        internal static string strPodajLiczbę2 {
            get {
                return ResourceManager.GetString("strPodajLiczbę2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekty.
        /// </summary>
        internal static string strProjekty {
            get {
                return ResourceManager.GetString("strProjekty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj początek przedziału.
        /// </summary>
        internal static string strPrzedział1 {
            get {
                return ResourceManager.GetString("strPrzedział1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj koniec przedziału.
        /// </summary>
        internal static string strPrzedział2 {
            get {
                return ResourceManager.GetString("strPrzedział2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        internal static string strRestart {
            get {
                return ResourceManager.GetString("strRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator Liczb Losowych.
        /// </summary>
        internal static string strRNG {
            get {
                return ResourceManager.GetString("strRNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silnia.
        /// </summary>
        internal static string strSilnia {
            get {
                return ResourceManager.GetString("strSilnia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma cyfr.
        /// </summary>
        internal static string strSumaCyfr {
            get {
                return ResourceManager.GetString("strSumaCyfr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma dzielników.
        /// </summary>
        internal static string strSumaDzielnikow {
            get {
                return ResourceManager.GetString("strSumaDzielnikow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suma z przedziału.
        /// </summary>
        internal static string strSumaPrzedzialu {
            get {
                return ResourceManager.GetString("strSumaPrzedzialu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systemy liczbowe.
        /// </summary>
        internal static string strSystemy {
            get {
                return ResourceManager.GetString("strSystemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ustaw funkcję.
        /// </summary>
        internal static string strUstaw {
            get {
                return ResourceManager.GetString("strUstaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wyjście.
        /// </summary>
        internal static string strWyjście {
            get {
                return ResourceManager.GetString("strWyjście", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorytmy zachłanne.
        /// </summary>
        internal static string strZachlanne {
            get {
                return ResourceManager.GetString("strZachlanne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miejsce zerowe funkcji.
        /// </summary>
        internal static string strZerowe {
            get {
                return ResourceManager.GetString("strZerowe", resourceCulture);
            }
        }
    }
}
